name: test
on: 
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Install golint
      run: go get -u golang.org/x/lint/golint
    - name: Install libpcsc
      run: sudo apt-get install -y libpcsclite-dev pcscd pcsc-tools
    - name: Test
      run: "PATH=$PATH:$( go env GOPATH )/bin make test"
